// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Chat.API.Database
{
    public partial class ChatRoomMessage
    {
        public int Id { get; set; }
        public int ChatRoomId { get; set; }
        public string UserName { get; set; }
        public string Message { get; set; }
        public DateTime Created { get; set; }
    }
}